### ISSUE TITLE
plist.bundle is missing architecture arm64e (M1 error with bundles)

### ISSUE THREAD

**Issue by jjeising** [textmate/bundle-support.tmbundle#34]
The bundled `Support/shared/lib/osx/plist.bundle` is missing architecture `arm64e` – can we do anything about it?
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(~/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/osx/plist.bundle, 0x0009): tried: '~/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/osx/plist.bundle' (fat file, but missing compatible architecture (have 'unknown,i386,x86_64', need 'arm64e')), '/usr/lib/plist.bundle' (no such file) - ~/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/osx/plist.bundle (LoadError)
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from ~/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/textmate.rb:5:in `<top (required)>'
⋮
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from Validate Bash:2:in `<main>'
```

**Comment by sorbits** [comment]
Code should switch to use the (native ruby) plist parser added in 7a6616709f04b247a916122acb9f1afc4c68be83.

See 300591a22adcc5560420a7d27137ab8b806d5f3c for an example of how this can be changed.
